//! [`Canvas`] — the drawing vocabulary, shared by the screen and the page.
//!
//! Four methods, named and shaped exactly like the [`Layer`] calls
//! `components/editor.rs` draws with, plus the measurement every one of
//! them depends on. That is the whole abstraction, and it is deliberately
//! not a general drawing API: `Layer` is the general drawing API, and this
//! is the subset a *document* is made of.
//!
//! Anything drawn through here is drawn identically on screen and in an
//! export, because it is one function either way. That is stronger than two
//! painters that agree today — see `PDF.md` §1. Everything a document has
//! but a session does not (a caret, a selection, a hover, a fold chevron)
//! stays in `editor.rs` against a `Layer` directly, which is why this trait
//! does not need to grow to cover it.
//!
//! A new element does not get a method here. It gets an arm in
//! `export/paint.rs`, and — if the editor and the page must not drift about
//! how it is drawn — a shared painter like `document::math_paint`.

use crate::layout::Rect;
use crate::renderer::{Alignment, Color, Layer, LineCap, LineJoin, PathPaint, Rounding, Stroke};
use crate::theme::{self, TextStyle};

/// Coordinates are logical pixels, top-left origin, y down. Whose origin is
/// the backend's business: the editor's is its pane, the exporter's is the
/// content column. Nothing drawn through this trait knows which.
pub trait Canvas {
    fn draw_rectangle(
        &mut self,
        at: (f32, f32),
        size: (f32, f32),
        color: Color,
        rounding: Rounding,
    );

    fn draw_circle(&mut self, center: (f32, f32), radius: f32, color: Color);

    /// An SVG path-data string in its own local units, placed by its origin.
    /// `rotation` is radians clockwise about the path's own bounding-box
    /// centre — zero is upright.
    ///
    /// A malformed `d` draws nothing rather than failing the call. Every
    /// path here is generated by layout or is a literal in this crate, so a
    /// parse error is a bug in the source, not a condition a page has to
    /// recover from; `Layer::draw_path` reports it and the call sites
    /// `expect` on it.
    fn draw_path(&mut self, d: &str, at: (f32, f32), rotation: f32, paint: &PathPaint);

    /// `at` is the point named by `align`, as in [`theme::draw`] — for the
    /// editor's body text that is the left edge at the line's vertical
    /// centre, not a baseline.
    fn draw_text(&mut self, text: &str, at: (f32, f32), style: &TextStyle, align: Alignment);

    /// How wide `text` sets — [`Layer::get_text_size`]'s width, and the
    /// number `document::layout` wrapped on.
    ///
    /// Measuring sits on the drawing trait for the same reason it sits on
    /// `Layer`: whatever draws the glyphs is the only thing that can say how
    /// much room they take, and a painter handed a separate measurer could
    /// be handed one that disagrees. It is also what lets a painter be
    /// tested against a recording canvas with no GPU behind it.
    fn measure(&self, text: &str, style: &TextStyle) -> f32;
}

/// A hairline, as [`theme::rule`] draws it.
pub fn rule(canvas: &mut dyn Canvas, at: (f32, f32), length: f32, thickness: f32, color: Color) {
    canvas.draw_rectangle(at, (length, thickness), color, Rounding::NONE);
}

/// A one-pixel border inside `rect`, as [`theme::outline`] draws it: four
/// rules rather than a stroked path, so the corners meet square.
pub fn outline(canvas: &mut dyn Canvas, rect: Rect, color: Color) {
    rule(canvas, rect.position(), rect.width, 1.0, color.clone());
    rule(
        canvas,
        (rect.x, rect.bottom() - 1.0),
        rect.width,
        1.0,
        color.clone(),
    );
    canvas.draw_rectangle(
        rect.position(),
        (1.0, rect.height),
        color.clone(),
        Rounding::NONE,
    );
    canvas.draw_rectangle(
        (rect.right() - 1.0, rect.y),
        (1.0, rect.height),
        color,
        Rounding::NONE,
    );
}

/// A rounded border inside `rect`, as [`theme::rounded_outline`] draws it:
/// one stroked path, so the corners are real quarter arcs that match a fill
/// drawn at the same radius. [`outline`]'s four rules cannot do that — they
/// square off whatever radius they are drawn around.
///
/// The geometry comes from [`theme::rounded_rect_path`], the same generator
/// the `Layer` painter strokes, so a highlight's border is the same shape on
/// screen and on a page.
pub fn rounded_outline(canvas: &mut dyn Canvas, rect: Rect, radius: f32, width: f32, color: Color) {
    let d = theme::rounded_rect_path(rect, radius);
    let mut pen = Stroke::new(color, width);
    pen.join = LineJoin::Round;
    canvas.draw_path(&d, (0.0, 0.0), 0.0, &PathPaint::Stroke(pen));
}

/// An open polyline in logical pixels, as [`theme::polyline`] strokes it:
/// round caps and joins, so a two-segment tick reads as one drawn stroke
/// rather than three shapes meeting. The `d` is built here rather than
/// taken as one, because a caller with a list of points has no business
/// formatting SVG.
pub fn polyline(canvas: &mut dyn Canvas, points: &[(f32, f32)], color: Color, thickness: f32) {
    let Some(((first_x, first_y), rest)) = points.split_first() else {
        return;
    };
    let mut d = format!("M{first_x} {first_y}");
    for (x, y) in rest {
        d.push_str(&format!("L{x} {y}"));
    }
    let mut pen = Stroke::new(color, thickness);
    pen.cap = LineCap::Round;
    pen.join = LineJoin::Round;
    canvas.draw_path(&d, (0.0, 0.0), 0.0, &PathPaint::Stroke(pen));
}

/// Another canvas with the origin moved. Everything drawn through it lands
/// `by` further along, and nothing drawn through it knows.
///
/// What this buys is a painter that only ever works in *its own* top-left
/// coordinates: a sidenote's body is a small `DocLayout` that starts at
/// `(0, 0)` like any other, and putting it in the margin is wrapping the
/// canvas rather than threading an origin through every function that draws
/// a piece of it. Sizes, radii and alignment are untouched — this moves the
/// origin, it does not scale or transform.
pub struct Offset<'a> {
    canvas: &'a mut dyn Canvas,
    by: (f32, f32),
}

impl<'a> Offset<'a> {
    pub fn new(canvas: &'a mut dyn Canvas, by: (f32, f32)) -> Self {
        Self { canvas, by }
    }

    fn at(&self, point: (f32, f32)) -> (f32, f32) {
        (point.0 + self.by.0, point.1 + self.by.1)
    }
}

impl Canvas for Offset<'_> {
    fn draw_rectangle(
        &mut self,
        at: (f32, f32),
        size: (f32, f32),
        color: Color,
        rounding: Rounding,
    ) {
        let at = self.at(at);
        self.canvas.draw_rectangle(at, size, color, rounding);
    }

    fn draw_circle(&mut self, center: (f32, f32), radius: f32, color: Color) {
        let center = self.at(center);
        self.canvas.draw_circle(center, radius, color);
    }

    fn draw_path(&mut self, d: &str, at: (f32, f32), rotation: f32, paint: &PathPaint) {
        let at = self.at(at);
        self.canvas.draw_path(d, at, rotation, paint);
    }

    fn draw_text(&mut self, text: &str, at: (f32, f32), style: &TextStyle, align: Alignment) {
        let at = self.at(at);
        self.canvas.draw_text(text, at, style, align);
    }

    fn measure(&self, text: &str, style: &TextStyle) -> f32 {
        self.canvas.measure(text, style)
    }
}

/// The screen. Every method forwards to the [`Layer`] call it is named
/// after, so a shared painter drawing through a `Canvas` queues exactly the
/// draw commands one holding the `Layer` itself would.
///
/// Implemented for `&Layer` rather than `Layer`: a layer is a cheap handle
/// with interior mutability and every one of its own methods takes `&self`,
/// so a component that has borrowed one can pass `&mut layer` here without
/// owning or cloning it. The trait asks for `&mut self` because the other
/// implementor — a PDF surface — genuinely accumulates.
impl Canvas for &Layer {
    fn draw_rectangle(
        &mut self,
        at: (f32, f32),
        size: (f32, f32),
        color: Color,
        rounding: Rounding,
    ) {
        Layer::draw_rectangle(self, at, size, color, rounding);
    }

    fn draw_circle(&mut self, center: (f32, f32), radius: f32, color: Color) {
        Layer::draw_circle(self, center, radius, color);
    }

    fn draw_path(&mut self, d: &str, at: (f32, f32), rotation: f32, paint: &PathPaint) {
        Layer::draw_path_rotated(self, d, at, rotation, paint.clone())
            .expect("every path drawn through a Canvas is generated or a literal");
    }

    fn draw_text(&mut self, text: &str, at: (f32, f32), style: &TextStyle, align: Alignment) {
        theme::draw(self, text, at, style, align);
    }

    fn measure(&self, text: &str, style: &TextStyle) -> f32 {
        theme::width(self, text, style)
    }
}
